### ISSUE TITLE
Error occurred when using limit.

### ISSUE THREAD

**Issue by CPWstatic** [vesoft-inc/nebula-graph#1168]
```
(root@nebula) [nba]> $a=get subgraph from "Tim Duncan"|limit 1;
[ERROR (-8)]: Internal error: empty column name list

Wed, 23 Jun 2021 17:14:20 CST
```

```
(root@nebula) [nba]> $a=go from "Tim Duncan" over * yield $$.player.name as name; limit 1
[ERROR (-8)]: Iterator should be kind of SequentialIter.
```

**Comment by Aiee** [comment]
```
(root@nebula) [nba]> get subgraph from "Tim Duncan"|limit 1;
2021/07/02 12:09:02 [ERROR] Failed to reconnect, failed to open transport, error: dial tcp 127.0.0.1:9669: connect: connection refused
2021/07/02 12:09:02 Loop error, failed to open transport, error: dial tcp 127.0.0.1:9669: connect: connection refused

Bye root!
Fri, 02 Jul 2021 12:09:02 CST

panic: Loop error, failed to open transport, error: dial tcp 127.0.0.1:9669: connect: connection refused

goroutine 1 [running]:
log.Panicf(0x78a345, 0xe, 0xc000317e78, 0x1, 0x1)
	/usr/local/go/src/log/log.go:358 +0xc0
main.main()
	/home/yichen.wang/Workspace/console/main.go:414 +0x4e1
```
![Screen Shot 2021-07-02 at 2 47 03 PM](https://user-images.githubusercontent.com/18348405/124232534-61342b00-db44-11eb-8d62-f8e434439ea9.png)
