### ISSUE TITLE
client crash with a statement

### ISSUE THREAD

**Issue by whitewum** [vesoft-inc/nebula-graph#723]
```
 WITH [1, 2, 3, 4, 5, NULL] AS a RETURN any(n IN a WHERE n > 2) AS r1

Bye user!
Mon, 01 Feb 2021 06:43:23 UTC

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x6d9fc6]

goroutine 1 [running]:
github.com/vesoft-inc/nebula-go.(*Session).Execute(0xc000156210, 0xc0001f2190, 0x44, 0x0, 0x0, 0x0)
        /go/pkg/mod/github.com/vesoft-inc/nebula-go@v1.1.1-0.20210120032134-ca7129eb9ccd/session.go:53 +0x406
main.loop(0xc000156210, 0x8168a0, 0xc000118180, 0x4, 0x8168a0)
        /usr/src/main.go:250 +0x22c
main.main()
        /usr/src/main.go:364 +0x403
```

**Comment by whitewum** [comment]
If possible, add to TCK tests.

**Comment by jievince** [comment]
Has fixed in https://github.com/vesoft-inc/nebula-graph/pull/734 and added it to tck tests.
