### ISSUE TITLE
graph crash

### ISSUE THREAD

**Issue by panda-sheep** [vesoft-inc/nebula-graph#761]
create edge follow(name string, age int, col3 bool); 
insert edge follow(name, age, col3) value 11 -> 22:("ddd", 1122, true);

GO FROM 11 OVER follow WHERE follow.age;

**Comment by panda-sheep** [comment]
```
#0  0x00000000027d0cd6 in nebula::graph::DeduceTypeVisitor::visit (this=0x7f84abbf94a0, expr=0x7f84a360c5e0)
    at /home/pandasheep.yue/nebula-2.0/nebula-graph/src/visitor/DeduceTypeVisitor.cpp:350
350         const_cast<LabelExpression*>(expr->left())->accept(this);
[Current thread is 1 (Thread 0x7f84abbfd700 (LWP 33630))]
Missing separate debuginfos, use: dnf debuginfo-install glibc-2.29-22.fc30.x86_64
(gdb) bt
#0  0x00000000027d0cd6 in nebula::graph::DeduceTypeVisitor::visit (this=0x7f84abbf94a0, expr=0x7f84a360c5e0)
    at /home/pandasheep.yue/nebula-2.0/nebula-graph/src/visitor/DeduceTypeVisitor.cpp:350
#1  0x0000000002b02d41 in nebula::LabelAttributeExpression::accept (this=0x7f84a360c5e0, visitor=0x7f84abbf94a0)
    at /home/pandasheep.yue/nebula-2.0/nebula-common/src/common/expression/LabelAttributeExpression.cpp:18
#2  0x0000000002695e91 in nebula::graph::Validator::deduceExprType (this=0x7f84a6e00500, expr=0x7f84a360c5e0) at /home/pandasheep.yue/nebula-2.0/nebula-graph/src/validator/Validator.cpp:353
#3  0x00000000026c8a6b in nebula::graph::GoValidator::validateWhere (this=0x7f84a6e00500, where=0x7f84a6e05050)
    at /home/pandasheep.yue/nebula-2.0/nebula-graph/src/validator/GoValidator.cpp:66
#4  0x00000000026c83aa in nebula::graph::GoValidator::validateImpl (this=0x7f84a6e00500) at /home/pandasheep.yue/nebula-2.0/nebula-graph/src/validator/GoValidator.cpp:26
#5  0x0000000002695191 in nebula::graph::Validator::validate (this=0x7f84a6e00500) at /home/pandasheep.yue/nebula-2.0/nebula-graph/src/validator/Validator.cpp:316
#6  0x00000000026e9184 in nebula::graph::SequentialValidator::validateImpl (this=0x7f84a6e4e000) at /home/pandasheep.yue/nebula-2.0/nebula-graph/src/validator/SequentialValidator.cpp:47
#7  0x0000000002695191 in nebula::graph::Validator::validate (this=0x7f84a6e4e000) at /home/pandasheep.yue/nebula-2.0/nebula-graph/src/validator/Validator.cpp:316
#8  0x000000000269465f in nebula::graph::Validator::validate (sentence=0x7f84a361c1e0, qctx=0x7f84a6e0b070) at /home/pandasheep.yue/nebula-2.0/nebula-graph/src/validator/Validator.cpp:267
#9  0x00000000025d5762 in nebula::graph::QueryInstance::validateAndOptimize (this=0x7f84a6e06120) at /home/pandasheep.yue/nebula-2.0/nebula-graph/src/service/QueryInstance.cpp:67
#10 0x00000000025d5154 in nebula::graph::QueryInstance::execute (this=0x7f84a6e06120) at /home/pandasheep.yue/nebula-2.0/nebula-graph/src/service/QueryInstance.cpp:36
#11 0x00000000025c3d39 in nebula::graph::QueryEngine::execute (this=0x7f84dc237ec0, rctx=...) at /home/pandasheep.yue/nebula-2.0/nebula-graph/src/service/QueryEngine.cpp:76
#12 0x00000000025a9c7b in nebula::graph::GraphService::future_execute (thi
```s=0x7f84dc237ea0, sessionId=1, query=...)
