### ISSUE TITLE
Crash occurs when the OR operator is used in the WHERE clause of the MATCH query.

### ISSUE THREAD

**Issue by RenmanKang** [vesoft-inc/nebula-graph#948]
**Describe the bug**

I ran the query below with the console, and there was a crash.

```
(root@nebula) [test]> MATCH (s:user)-[:follow]->(t:user) \
                   -> WHERE s.id == "u00000000000000000000000000000001" OR s.id == "u00000000000000000000000000000002" \
                   -> RETURN s.id AS sid, t.id AS tid
2021/04/13 22:41:40 [ERROR] Failed to reconnect, Failed to open transport, error: dial tcp 127.0.0.1:9669: connect: connection refused
2021/04/13 22:41:40 Loop error, Failed to open transport, error: dial tcp 127.0.0.1:9669: connect: connection refused

Bye root!
Tue, 13 Apr 2021 22:41:40 JST

panic: Loop error, Failed to open transport, error: dial tcp 127.0.0.1:9669: connect: connection refused

goroutine 1 [running]:
log.Panicf(0x624b08, 0xe, 0xc000047e78, 0x1, 0x1)
        /usr/local/go/src/log/log.go:361 +0xc5
main.main()
        /home1/irteamsu/nebula-console/main.go:386 +0x4f3
```

**Environments**
* OS
```
Linux nebula001-dev 3.10.0-1160.11.1.el7.x86_64 #1 SMP Fri Dec 18 16:34:56 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```
* Nebula Version: Nebula RPM package
```
nebula-graph-2.0.0.el7.x86_64.rpm
```
* CPU Info 
```
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                4
...
Model name:            Intel(R) Xeon(R) Silver 4210 CPU @ 2.20GHz
...
```
* Service Architecture
  * metad: 3ea
  * graphd: 3ea
  * storaged: 3ea

**How To Reproduce**
1. Create tag & edge type
```
CREATE TAG user(id fixed_string(33), type int, region fixed_string(2), crtm timestamp);
CREATE TAG INDEX user_idx_id on user(id);
REBUILD TAG INDEX user_idx_id

CREATE EDGE follow(crtm int);
```
2. Insert vertex & edge
```
INSERT VERTEX user (id, type, region, crtm) VALUES "u00000000000000000000000000000001":("u00000000000000000000000000000001", 1, "JP", now()); /* 1 million data inserts */
INSERT EDGE follow(crtm) VALUES "u00000000000000000000000000000001"->"u00000000000000000000000000000002":(now()) /* 1 million data inserts */
```
3. Execute Match Query
```
MATCH (s:user)-[:follow]->(t:user) \
WHERE s.id == "u00000000000000000000000000000001" OR s.id == "u10002" OR s.id == "u00000000000000000000000000000002" \
RETURN s.id AS sid, t.id AS tid
```

**Expected behavior**
The results of the query shall be as follows:
```
+-------------------------------------+-------------------------------------+
| sid                                 | tid                                 |
+-------------------------------------+-------------------------------------+
| "u00000000000000000000000000000001" | "u00000000000000000000000000000002" |
+-------------------------------------+-------------------------------------+
| "u00000000000000000000000000000001" | "u00000000000000000000000000000003" |
+-------------------------------------+-------------------------------------+
| "u00000000000000000000000000000001" | "u00000000000000000000000000000004" |
+-------------------------------------+-------------------------------------+
... more ...
```

**Comment by CPWstatic** [comment]
Sorry for the trouble, but i didn't reproduce this problem. Would please provide more informations? such as the logs, core file.

**Comment by RenmanKang** [comment]
The crash log is not found in the error log files(nebula-storaged.ERROR, storaged-stderr.log).
I can't find where the core file is, so can I know what the core file path is?

**Comment by CPWstatic** [comment]
Did you find anything in nebula-graph logs? And you might find the core files by following the path defined in `/proc/sys/kernel/core_pattern`.

**Comment by CPWstatic** [comment]
According to your description, the problem might occurs at one of the three nebula-graphd, so you have to check which one had crashed and get the logs.

**Comment by RenmanKang** [comment]
Nothing found in nebula-graph logs.
And I looked it up as you said, but the core file was not created either.

**Comment by CPWstatic** [comment]
That's weird, is this a case that could be reproduced in your environment? And would you please make sure that the daemons (graphd, metad, storage) are all healthy? And make sure you console is updated to the corresponding version.

**Comment by czpmango** [comment]
I didn‘t reproduce the error either, this is my local test:
```
(czp@nebula) [test]> DROP space test;
Execution succeeded (time spent 3216/3821 us)

(czp@nebula) [(none)]> CREATE SPACE test(VID_TYPE=FIXED_STRING(40));
Execution succeeded (time spent 2620/3009 us)

(czp@nebula) [(none)]> use test;
Execution succeeded (time spent 1610/2199 us)

(czp@nebula) [test]> CREATE TAG user(id fixed_string(33), type int, region fixed_string(2), crtm timestamp);
Execution succeeded (time spent 1918/2207 us)

(czp@nebula) [test]> CREATE TAG INDEX user_idx_id on user(id);
Execution succeeded (time spent 1459/1613 us)

(czp@nebula) [test]> CREATE EDGE follow(crtm int);
Execution succeeded (time spent 2575/3113 us)

(czp@nebula) [test]> REBUILD TAG INDEX user_idx_id;
+------------+
| New Job Id |
+------------+
| 46         |
+------------+
Got 1 rows (time spent 2206/2769 us)

(czp@nebula) [test]> SHOW JOBS;
+--------+---------------------+------------+-------------------------+-------------------------+
| Job Id | Command             | Status     | Start Time              | Stop Time               |
+--------+---------------------+------------+-------------------------+-------------------------+
| 46     | "REBUILD_TAG_INDEX" | "FINISHED" | 2021-04-17T03:24:42.000 | 2021-04-17T03:24:42.000 |
+--------+---------------------+------------+-------------------------+-------------------------+

(czp@nebula) [test]> INSERT VERTEX user (id, type, region, crtm) VALUES "u00000000000000000000000000000001":("u00000000000000000000000000000001", 1, "JP", now()); /* 1 million data inserts */
Execution succeeded (time spent 2150/2417 us)

(czp@nebula) [test]> INSERT VERTEX user (id, type, region, crtm) VALUES "u00000000000000000000000000000002":("u00000000000000000000000000000002", 1, "JP", now()); /* 1 million data inserts */
Execution succeeded (time spent 693/848 us)

(czp@nebula) [test]> INSERT EDGE follow(crtm) VALUES "u00000000000000000000000000000001"->"u00000000000000000000000000000002":(now()) /* 1 million data inserts */
Execution succeeded (time spent 2247/2850 us)

(czp@nebula) [test]> MATCH (s:user)-[:follow]->(t:user) \
                  -> WHERE s.id == "u00000000000000000000000000000001" OR s.id == "u10002" OR s.id == "u00000000000000000000000000000002" \
                  -> RETURN s.id AS sid, t.id AS tid;
+-------------------------------------+-------------------------------------+
| sid                                 | tid                                 |
+-------------------------------------+-------------------------------------+
| "u00000000000000000000000000000001" | "u00000000000000000000000000000002" |
+-------------------------------------+-------------------------------------+
Got 1 rows (time spent 8680/9344 us)
```

**Comment by czpmango** [comment]
One thing you need to know is that you created a null-point when you insert an edge that end point didn't exist, the tag of the null-point is not `user`.

**Comment by czpmango** [comment]
> That's weird, is this a case that could be reproduced in your environment? And would you please make sure that the daemons (graphd, metad, storage) are all healthy? And make sure you console is updated to the corresponding version.

I agree with that, plz ensure the above conditions. @RenmanKang  We will be looking forward to your feedback.

**Comment by RenmanKang** [comment]
I created a new graph space and tested it again.
It generated 1 million user vertices(vid: u00000000000000000000000000000001 ~ u00000000000000000000000001000000) and about 500,000 follow edges.
Then i ran the following query.
```
MATCH (s:user)-[:follow]->(t:user) \
  WHERE s.id == "u00000000000000000000000000000001" \
  OR s.id == "u00000000000000000000000000000002" \
  OR s.id == "u00000000000000000000000000000003" \
  RETURN s.id AS sid, t.id AS tid;

+-------------------------------------+-------------------------------------+
| sid                                 | tid                                 |
+-------------------------------------+-------------------------------------+
| "u00000000000000000000000000000001" | "u00000000000000000000000000000001" |
+-------------------------------------+-------------------------------------+
| "u00000000000000000000000000000001" | "u00000000000000000000000000000002" |
+-------------------------------------+-------------------------------------+
| "u00000000000000000000000000000002" | "u00000000000000000000000000000010" |
+-------------------------------------+-------------------------------------+
... more ...

Got 662 rows (time spent 383615745/383511260 us)
```

There was no crash this time. But the query took too long.
It takes 383,615,745us(383sec) even though user.id has index.
I don't understand why it takes so long.

Anyway, since then, I have added about 500,000 more follow edges(total 1 million edges) and run the same query. Then a crash occurred.
```
MATCH (s:user)-[:follow]->(t:user)   WHERE s.id == "u00000000000000000000000000000001"   OR s.id == "u00000000000000000000000000000002"   OR s.id == "u00000000000000000000000000000003"   RETURN s.id AS sid, t.id AS tid;
2021/04/18 21:06:26 [ERROR] Failed to reconnect, Failed to open transport, error: dial tcp 127.0.0.1:9669: connect: connection refused
2021/04/18 21:06:26 Loop error, Failed to open transport, error: dial tcp 127.0.0.1:9669: connect: connection refused

Bye root!
Sun, 18 Apr 2021 21:06:26 JST

panic: Loop error, Failed to open transport, error: dial tcp 127.0.0.1:9669: connect: connection refused

goroutine 1 [running]:
log.Panicf(0x624b08, 0xe, 0xc000093e78, 0x1, 0x1)
        /usr/local/go/src/log/log.go:361 +0xc5
main.main()
        /home1/irteamsu/nebula-console/main.go:386 +0x4f3
```

Given the above circumstances, this seems to be a memory problem(All three test servers are using 8GB of memory).
If the number of edges is large, there seems to be a problem with using the OR operator in the MATCH query... Is this a normal situation? Is there any solution to this?

On the other hand, querying with vid takes much shorter.

```
MATCH (s:user)-[:follow]->(t:user) \
  WHERE id(s) == "u00000000000000000000000000000001" \
  OR id(s) == "u00000000000000000000000000000002" \
  OR id(s) == "u00000000000000000000000000000003" \
  RETURN s.id AS sid, t.id AS tid;

+-------------------------------------+-------------------------------------+
| sid                                 | tid                                 |
+-------------------------------------+-------------------------------------+
| "u00000000000000000000000000000001" | "u00000000000000000000000000000001" |
+-------------------------------------+-------------------------------------+
| "u00000000000000000000000000000001" | "u00000000000000000000000000000002" |
+-------------------------------------+-------------------------------------+
| "u00000000000000000000000000000002" | "u00000000000000000000000000000010" |
+-------------------------------------+-------------------------------------+
... more ...

Got 662 rows (time spent 290154/291801 us)
```

**Comment by czpmango** [comment]
Bcz `s.id` is an attribute filter and needs to scan all data to find the starting points, it is not necessary to query with vid directly. You can `profile` the query to get the execution cost.

**Comment by CPWstatic** [comment]
We had found the problem due to your detailed description, it is because we did not provide an efficient execution plan which would lead to full tag scan which finally caused the OOM on your environment. We will improve it as soon as possible. For now, you could turn to the alternative usage which you had already found:
```
MATCH (s:user)-[:follow]->(t:user) \
  WHERE id(s) == "u00000000000000000000000000000001" \
  OR id(s) == "u00000000000000000000000000000002" \
  OR id(s) == "u00000000000000000000000000000003" \
  RETURN s.id AS sid, t.id AS tid;
```
Again, sorry for the trouble.
